# Generated by Django 5.0 on 2023-12-05 20:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estatedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_of_estate_representative', models.CharField(max_length=100)),
                ('last_name_of_estate_representative', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('picture', models.ImageField(upload_to=None)),
                ('estate_name', models.CharField(max_length=100)),
                ('estate_location', models.CharField(max_length=100)),
                ('excos', models.BooleanField()),
                ('number_of_excos', models.IntegerField()),
                ('estate_worker', models.BooleanField()),
                ('number_of_estate_workers', models.IntegerField()),
                ('residents', models.BooleanField()),
                ('number_of_residents', models.IntegerField()),
            ],
        ),
    ]
