# Generated by Django 5.0 on 2023-12-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatedata',
            name='picture',
            field=models.ImageField(default='Images/None/Noimg.jpg', upload_to='Images'),
        ),
    ]
